google.maps.__gjsload__('infowindow', function(_){var GOa=function(a,b){if(a.qh.size===1){let c=Array.from(a.qh.values())[0];c.Zs!==b.Zs&&(c.set("map",null),a.qh.delete(c))}a.qh.add(b)},IOa=function(a,b,c=!1){var d=a.__gm;a=d.get("panes");d=d.get("innerContainer");b={on:a,Mj:_.TA.Mj(),GA:d,shouldFocus:b,Zs:c};return new HOa(b)},VK=function(a,b){a.container.style.visibility=b?"":"hidden";b&&a.shouldFocus&&(a.focus(),a.shouldFocus=!1);b?JOa(a):a.Dh=!1},KOa=function(a){a.Rj.setAttribute("aria-labelledby",a.th.id)},LOa=function(a){var b=!!a.get("open"),
c=a.get("content");c=b?c:null;if(c===a.xh)VK(a,b&&a.get("position"));else{if(a.xh){let d=a.xh.parentNode;d===a.qh&&d.removeChild(a.xh)}c&&(a.Bh=!1,a.qh.appendChild(c));VK(a,b&&a.get("position"));a.xh=c;WK(a)}},XK=function(a){var b=!!a.get("open"),c=a.get("headerContent"),d=!!a.get("ariaLabel"),e=a.get("headerDisabled"),f=!!a.get("isPoi"),g=!e;b=b?c:null;c=f&&e;a.Rj.style.paddingTop=!f&&e?"12px":"0";e=a.Rj;c?_.Gv(e,"gm-style-iw-poi"):_.PE(e,"gm-style-iw-poi");_.ap.qh&&!_.ap.yh&&(a.qh.style.overflow=
c?"auto":"scroll");b===a.yh?a.sh.style.display=g?"":"none":(a.yh&&(e=a.yh.parentNode,e===a.th&&e.removeChild(a.yh)),b&&(a.Bh=!1,a.th.appendChild(b),g&&!d&&KOa(a)),a.sh.style.display=g?"":"none",a.yh=b,WK(a))},YK=function(a,b){var c=!!a.get("isPoi");a=!!a.get("headerDisabled");c&&a&&b instanceof HTMLElement&&(b.style.outline="none");return _.hp(b,!0)},WK=function(a){var b=a.getSize();if(b){var c=b.oo;b=b.minWidth;a.Rj.style.maxWidth=_.vl(c.width);a.Rj.style.maxHeight=_.vl(c.height);a.Rj.style.minWidth=
_.vl(b);b=!!a.get("headerDisabled");b=!!a.get("isPoi")&&b;a.qh.style.maxHeight=_.ap.qh?_.vl(c.height-(b?0:18)):_.vl(c.height-(b?0:36));ZK(a);a.Ah.start()}},MOa=function(a){var b=a.get("pixelOffset")||new _.tn(0,0),c=new _.tn(a.Rj.offsetWidth,a.Rj.offsetHeight);a=-b.height+c.height+11+60;var d=b.height+60,e=-b.width+c.width/2+60;c=b.width+c.width/2+60;b.height<0&&(d-=b.height);return{top:a,bottom:d,left:e,right:c}},JOa=function(a){!a.Dh&&a.get("open")&&a.get("visible")&&a.get("position")&&(_.Hm(a,
"visible"),a.Dh=!0)},ZK=function(a){var b=a.get("position");if(b&&a.get("pixelOffset")){var c=MOa(a);let d=b.x-c.left,e=b.y-c.top,f=b.x+c.right;c=b.y+c.bottom;_.Kv(a.anchor,b);b=a.get("zIndex");_.Mv(a.container,_.pl(b)?b:e+60);a.set("pixelBounds",_.Mn(d,e,f,c))}},OOa=function(a,b,c){return b instanceof _.Wm?new NOa(a,b,c):new NOa(a,b)},QOa=function(a){a.qh&&a.Qi.push(_.Fm(a.qh,"pixelposition_changed",()=>{POa(a)}))},POa=function(a){var b=a.model.get("pixelPosition")||a.qh&&a.qh.get("pixelPosition");
a.th.set("position",b)},SOa=function(a){a=a.__gm;a.get("IW_AUTO_CLOSER")||a.set("IW_AUTO_CLOSER",new ROa);return a.get("IW_AUTO_CLOSER")},ROa=class{constructor(){this.qh=new Set}};var HOa=class extends _.Jm{constructor(a){super();this.xh=this.yh=this.zh=null;this.Dh=this.Bh=!1;this.GA=a.GA;this.shouldFocus=a.shouldFocus;this.container=document.createElement("div");this.container.style.cursor="default";this.container.style.position="absolute";this.container.style.left=this.container.style.top="0";a.on.floatPane.appendChild(this.container);this.anchor=document.createElement("div");this.container.appendChild(this.anchor);this.wh=document.createElement("div");this.anchor.appendChild(this.wh);
this.Rj=document.createElement("div");this.wh.appendChild(this.Rj);this.Rj.setAttribute("role","dialog");this.Rj.tabIndex=-1;this.sh=document.createElement("div");this.Rj.appendChild(this.sh);this.th=document.createElement("div");this.sh.appendChild(this.th);this.Fh=document.createElement("div");this.wh.appendChild(this.Fh);this.qh=document.createElement("div");this.Rj.appendChild(this.qh);_.qFa(this.container);_.Gv(this.Rj,"gm-style-iw");_.Gv(this.anchor,"gm-style-iw-a");_.Gv(this.wh,"gm-style-iw-t");
_.Gv(this.Fh,"gm-style-iw-tc");_.Gv(this.Rj,"gm-style-iw-c");_.Gv(this.sh,"gm-style-iw-chr");_.Gv(this.th,"gm-style-iw-ch");_.Gv(this.qh,"gm-style-iw-d");this.set("isPoi",a.Zs);this.th.setAttribute("id",_.Vm());_.ap.qh&&!_.ap.yh&&(this.Rj.style.paddingInlineEnd="0",this.Rj.style.paddingBottom="0",this.qh.style.overflow="scroll");VK(this,!1);_.Bm(this.container,"mousedown",_.tm);_.Bm(this.container,"mouseup",_.tm);_.Bm(this.container,"mousemove",_.tm);_.Bm(this.container,"pointerdown",_.tm);_.Bm(this.container,
"pointerup",_.tm);_.Bm(this.container,"pointermove",_.tm);_.Bm(this.container,"dblclick",_.tm);_.Bm(this.container,"click",_.tm);_.Bm(this.container,"touchstart",_.tm);_.Bm(this.container,"touchend",_.tm);_.Bm(this.container,"touchmove",_.tm);_.wv(this.container,"contextmenu",this,this.Gh);_.wv(this.container,"wheel",this,_.tm);a=new _.pn(12,12);var b=new _.tn(24,24);this.rh=new _.cq({Xs:a,Eu:b,offset:new _.pn(-6,-6),mF:!0,ownerElement:this.sh});this.sh.appendChild(this.rh.element);_.Bm(this.rh.element,
"click",c=>{_.tm(c);_.Hm(this,"closeclick");this.set("open",!1)});this.Ah=new _.Ho(()=>{!this.Bh&&this.get("content")&&this.get("visible")&&(_.Hm(this,"domready"),this.Bh=!0)},0);this.Eh=_.Bm(this.container,"keydown",c=>{c.key!=="Escape"&&c.key!=="Esc"||!this.Rj.contains(document.activeElement)||(c.stopPropagation(),_.Hm(this,"closeclick"),this.set("open",!1))})}ariaLabel_changed(){var a=this.get("ariaLabel");a?this.Rj.setAttribute("aria-label",a):(this.Rj.removeAttribute("aria-label"),this.get("headerDisabled")||
KOa(this))}open_changed(){LOa(this);XK(this)}headerContent_changed(){XK(this)}headerDisabled_changed(){XK(this)}content_changed(){LOa(this)}pendingFocus_changed(){this.get("pendingFocus")&&(this.get("open")&&this.get("visible")&&this.get("position")?YK(this,this.Rj):console.warn("Setting focus on InfoWindow was ignored. This is most likely due to InfoWindow not being visible yet."),this.set("pendingFocus",!1))}dispose(){setTimeout(()=>{document.activeElement&&document.activeElement!==document.body||
(this.zh&&this.zh!==document.body?YK(this,this.zh)||YK(this,this.GA):YK(this,this.GA))});this.Eh&&_.xm(this.Eh);this.container.parentNode.removeChild(this.container);this.Ah.stop();this.Ah.dispose()}getSize(){var a=this.get("layoutPixelBounds"),b=this.get("pixelOffset"),c=this.get("maxWidth")||648,d=this.get("minWidth")||0;if(!b)return null;a?(b=a.maxY-a.minY-(11+-b.height),a=a.maxX-a.minX-6,a>=240&&(a-=120),b>=240&&(b-=120)):(a=648,b=654);a=Math.min(a,c);a=Math.max(d,a);a=Math.max(0,a);b=Math.max(0,
b);return{oo:new _.tn(a,b),minWidth:d}}pixelOffset_changed(){var a=this.get("pixelOffset")||new _.tn(0,0);this.wh.style.right=_.vl(-a.width);this.wh.style.bottom=_.vl(-a.height+11);WK(this)}layoutPixelBounds_changed(){WK(this)}position_changed(){this.get("position")?(ZK(this),VK(this,!!this.get("open"))):VK(this,!1)}zIndex_changed(){ZK(this)}visible_changed(){this.container.style.display=this.get("visible")?"":"none";this.Ah.start();if(this.get("visible")){let a=this.rh.element.style.display;this.rh.element.style.display=
"none";this.rh.element.getBoundingClientRect();this.rh.element.style.display=a;JOa(this)}else this.Dh=!1}Gh(a){for(var b=!1,c=this.get("content"),d=a.target;!b&&d;)b=d===c,d=d.parentNode;b?_.qm(a):_.sm(a)}focus(){this.zh=document.activeElement;var a;_.ap.Bh&&(a=this.qh.getBoundingClientRect());if(this.get("disableAutoPan"))YK(this,this.Rj);else{var b=_.Qv(this.qh);if(b.length){b=b[0];a=a||this.qh.getBoundingClientRect();var c=b.getBoundingClientRect();YK(this,c.bottom<=a.bottom&&c.right<=a.right?
b:this.Rj)}else YK(this,this.rh.element)}}};var NOa=class{constructor(a,b,c){this.model=a;this.isOpen=!0;this.qh=this.sh=this.Sh=null;this.Qi=[];var d=a.get("shouldFocus");this.th=IOa(b,d,a.Zs);var e=b.__gm;(d=b instanceof _.Wm)&&c?c.then(h=>{this.isOpen&&(this.Sh=h,this.qh=new _.LI(k=>{this.sh=new _.pA(b,h,k,()=>{});h.Qj(this.sh);return this.sh}),this.qh.bindTo("latLngPosition",a,"position"),QOa(this))}):(this.qh=new _.LI,this.qh.bindTo("latLngPosition",a,"position"),this.qh.bindTo("center",e,"projectionCenterQ"),this.qh.bindTo("zoom",e),
this.qh.bindTo("offset",e),this.qh.bindTo("projection",b),this.qh.bindTo("focus",b,"position"),QOa(this));this.wh=d?a.infoWindow.get("logAsInternal")?148284:148285:null;var f=new _.yI(["scale"],"visible",h=>h==null||h>=.3);this.qh&&f.bindTo("scale",this.qh);var g=this.th;g.set("logAsInternal",!!a.infoWindow.get("logAsInternal"));g.bindTo("ariaLabel",a);g.bindTo("zIndex",a);g.bindTo("layoutPixelBounds",e,"pixelBounds");g.bindTo("disableAutoPan",a);g.bindTo("pendingFocus",a);g.bindTo("maxWidth",a);
g.bindTo("minWidth",a);g.bindTo("content",a);g.bindTo("headerContent",a);g.bindTo("headerDisabled",a);g.bindTo("pixelOffset",a);g.bindTo("visible",f);this.rh=new _.Ho(()=>{if(b instanceof _.Wm)if(this.Sh){var h=a.get("position");h&&_.koa(b,this.Sh,new _.bn(h),MOa(g))}else c.then(()=>{this.rh.start()});else(h=g.get("pixelBounds"))?_.Hm(e,"pantobounds",h):this.rh.start()},150);if(d){let h=null;this.Qi.push(_.Fm(a,"position_changed",()=>{var k=a.get("position");!k||a.get("disableAutoPan")||k.equals(h)||
(this.rh.start(),h=k)}))}else a.get("disableAutoPan")||this.rh.start();g.set("open",!0);this.Qi.push(_.vm(g,"domready",()=>{a.trigger("domready")}));this.Qi.push(_.vm(g,"visible",()=>{a.trigger("visible")}));this.Qi.push(_.vm(g,"closeclick",()=>{a.close();a.trigger("closeclick")}));this.Qi.push(_.Fm(a,"pixelposition_changed",()=>{POa(this)}));this.wh&&_.P(b,this.wh)}close(){if(this.isOpen){this.isOpen=!1;this.model.trigger("close");for(var a of this.Qi)_.xm(a);this.Qi.length=0;this.rh.stop();this.rh.dispose();
this.Sh&&this.sh&&this.Sh.ym(this.sh);a=this.th;a.unbindAll();a.set("open",!1);a.dispose();this.qh&&this.qh.unbindAll()}}};_.Sk("infowindow",{wL:function(a){var b=null;_.Fm(a,"map_changed",function d(){var e=a.get("map");b&&(b.yG.qh.delete(a),b.pP.close(),b=null);if(e){let f=e.__gm;f.get("panes")?f.get("innerContainer")?(b={pP:OOa(a,e,e instanceof _.Wm?f.rh.then(({Sh:g})=>g):void 0),yG:SOa(e)},GOa(b.yG,a)):_.Em(f,"innercontainer_changed",d):_.Em(f,"panes_changed",d)}})}});});
